{% set name = "neurosynchro" %}
{% set version = "0.1.4" %}
{% set sha256 = "16f22a1362bcfb3cc0115f7cd5fcd8943007a0891f0d2041713ec00ef49f94e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - neurosynchro = neurosynchro.cli:main

requirements:
  build:
    - pip
    - python
  run:
    - python
    - keras
    - numpy
    - pandas
    - pwkit
    - pytoml
    - six

test:
  imports:
    - neurosynchro
    - neurosynchro.cli
    - neurosynchro.impl
    - neurosynchro.train

about:
  home: https://github.com/pkgw/neurosynchro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Train and use neural networks to quickly approximate polarized synchrotron radiative transfer coefficients.'

  description: |
    Neurosynchro is a small Python package for creating and using neural
    networks to quickly approximate the coefficients needed for
    fully-polarized synchrotron radiative transfer. It builds on the Keras
    deep learning library.
  doc_url: http://neurosynchro.readthedocs.io/
  dev_url: https://github.com/pkgw/neurosynchro

extra:
  recipe-maintainers:
    - pkgw
