travis:
  secure:
    BINSTAR_TOKEN: TSUuSRud3i0CrzfNiFx/9xXvnZ99tiKL7rcg9scBRn9GUwvQpaW1+3gxDTwhgH0yoM5RiIkb+SrmWA8cHtHWHFnEGPJhr1ZlwfilOzaKW4n0GNfWjqK2h+OxCSKsOfmLMQQWsHsSAV3ZaBcIjpx6/3UG6dB2Ylm6bl+qi9Lo4Cy+x7FH3g0AB4omGKcJZhK9pjjxUOTS1e67Pw/lDQCf9aJQ2ufsV3kYcSEA8MZAuqp/OpqbvfCMtaIAWh7+Qnzk3L52q6dWAdyno5gj1gus+k0rRrQMs/gc27pTv72A9bqweSgmK6qWoQZ/M9MfmucsUlnCpd296JhERedOf+Ho9p3bEkNn0o89iZFWoz1CbB/SOiGxjM5ZdcCP/CDHoMkts5wVwkNrzpvqZgVFXVVghz5b5mXfSQPcFJLEefIxPbM6Apz0/d+x0rgVVrxBpZwwUl4Fe/FTyEoNqp7DQx8VcayPFZmAgV98mYLkjpTV2OIh112FrtUL9OsKQdJo+bzU/Fa/mXCi265YvmuJQpVeIZ/P9CEbFsB2QWWgHspmt6Z/ayOvaKJJfhXp2qWWWAztqP0PiBuz3qrnIqhZKOGiby41UggyBgSoMjeQ0s/HqHtdf9IhYRzWS3T9GFx752yFcvk4yMiD1nx/RmjtpH7pvRW38wATl5XoXib/8y5Ge7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
